name: Build
on:
  push:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Set up JDK 23
      uses: actions/setup-java@main
      with:
        java-version: 22
        distribution: temurin

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@main

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Assemble
      run: ./gradlew assembleRelease

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@main
      with:
        name: Unitto
        path: app/build/outputs/apk/*
